# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:35
from __future__ import unicode_literals

import Tagent3.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20, validators=[Tagent3.validators.validate_city])),
                ('state', models.CharField(max_length=20, validators=[Tagent3.validators.validate_state])),
                ('landmark', models.CharField(max_length=20, validators=[Tagent3.validators.validate_landmark])),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentReferals',
            fields=[
                ('referal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, validators=[Tagent3.validators.validate_name])),
                ('verified', models.BinaryField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, validators=[Tagent3.validators.validate_mobile_no])),
                ('phone_number', models.CharField(max_length=15, validators=[Tagent3.validators.validate_phone_no])),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=20, validators=[Tagent3.validators.validate_loc_name])),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=50, validators=[Tagent3.validators.validate_media_name])),
                ('media_path', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Tagent3.Media')),
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Tagent3.ContactInfo')),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[Tagent3.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=20, validators=[Tagent3.validators.validate_last_name])),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50, validators=[Tagent3.validators.validate_education])),
                ('company_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100, validators=[Tagent3.validators.validate_specelization])),
                ('experence', models.IntegerField()),
                ('agent_notes', models.TextField()),
                ('address', models.ManyToManyField(to='Tagent3.Address')),
                ('agentreferal', models.ManyToManyField(to='Tagent3.AgentReferals')),
                ('location', models.ManyToManyField(to='Tagent3.Location')),
                ('propertytype', models.ManyToManyField(to='Tagent3.PropertyType')),
            ],
            bases=('Tagent3.contactinfo', 'Tagent3.media'),
        ),
    ]
